parameters:
- name: WebAppEnvironment
  default: ''
- name: WebAppName
  default: ''
- name: AzSubscription
  default: ''

jobs:
- deployment: Deploy
  environment: '${{ parameters.WebAppEnvironment }}'
  pool:
    vmImage: 'windows-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: '${{ parameters.AzSubscription }}'
            appType: 'webApp'
            WebAppName: '${{ parameters.WebAppName }}'
            packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'
            enableCustomDeployment: true
            DeploymentType: 'webDeploy'
